### ISSUE TITLE
Maintain request

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/helm-ag#341]
@tarsius I have post the request in this post here => [Missing maintainer, @syohex](https://github.com/melpa/melpa/issues/6674). But I think some how you end it up not seeing it. So I decide to post it here.

I would like to help maintaining these packages! If there is already people maintaining it, that's good for me! Thanks! :D

* zoom-window
* fontawesome
* sound-wav
* counsel-gtags
* helm-themes
* helm-gtags
* helm-ag

**Comment by tarsius** [comment]
`counsel-gtags` did not get transferred because I erroneously dropped the `emacs-` prefix in the transfer script. But that's okay. @FelipeLema adopted it a year ago and his fork is what Melpa uses. Unfortunately the original repository was not transferred when he took over, but since his repository has a dozen topics as well, it is to late for that now.

**Comment by jcs090218** [comment]
Oh, I see. No worries! If there are other maintainer willing to take over then let them take it! I am just willing to maintain these package because either I have some experience with or I am interested in these packages. All good! :D
